#!/usr/bin/env python3
"""Emit ports/vulkan/shaders/gdn_rec_chunk_reg.comp - the register-resident variant of the chunk recurrence.

WHY GENERATED.  The shipped and KU chunk shaders keep the (S=128) state column in `float st[SL]`, and glslc will
not promote a dynamically indexed 128-element array into registers - it compiled it into per-invocation memory
(the SPIR-V keeps `OpLoopMerge`, so the loops stayed rolled).  The measured consequence is that the per-token cost
is invariant to the dispatch count and to the unroll factor: ~370-390 us per (layer, token), which is the exposed
latency of re-touching that column 2-3 times per token with nothing to overlap it against.  This variant removes
the array entirely: 128 NAMED SCALARS, straight-line code, constant indices - the only shape a compiler can keep
in registers.

BIT-EXACTNESS IS THE POINT, SO THE EMITTED ORDER IS MECHANICAL.  The arithmetic below is the shipped
`native_gdn_step`'s, spelled out one element at a time, in the same single ascending-i order that the rolled and
KU versions use (`(0 + t0) + t1 ...`, never reassociated).  Both the `sk` contract and the readout keep ONE
accumulator; the update is the same `g*s + k*delta`; the readout scale is the same fused 1/sqrt(S).  If the ids
move, that is a finding about the compiler, not a licence to widen a tolerance.

Run:  python3 gen_gdn_rec_reg.py > ports/vulkan/shaders/gdn_rec_chunk_reg.comp
"""
import sys

SL = 128

HEAD = """#version 450
// ports/vulkan/shaders/gdn_rec_chunk_reg.comp - GENERATED by scripts/gen_gdn_rec_reg.py.  DO NOT HAND-EDIT.
//
// The REGISTER-RESIDENT form of the prompt-chunk GDN recurrence: 128 named scalars hold the state column across
// the token walk, with every index a compile-time constant, so the compiler has a shape it can keep in registers
// (the shipped/KU versions' `float st[128]` is dynamically indexed and compiled into per-invocation memory).
//
// ARITHMETIC IS THE SHIPPED KERNEL'S, ELEMENT FOR ELEMENT, IN THE SAME ASCENDING-i ORDER - one accumulator for
// the `sk` contract, one for the readout, the same `g*s + k*delta` update, the same fused 1/sqrt(S) scale.  No
// sum is reassociated, so this is not the parallel scan the port rejected on the recurrence's chaos.  The TOKEN
// axis is still walked SERIALLY (see gdn_rec_chunk.comp's header for the full argument).
layout(local_size_x = 256) in;
layout(set = 0, binding = 0, std430) buffer STATE { float v[]; } state;      // (S, h_v, S), j fastest, in place
layout(set = 0, binding = 1, std430) readonly buffer QKV { float v[]; } qkv;  // (T, (2*h_k + h_v)*S)
layout(set = 0, binding = 2, std430) readonly buffer G { float v[]; } gb;     // (T, h_v) pre-exp gate
layout(set = 0, binding = 3, std430) readonly buffer B { float v[]; } bb;     // (T, h_v) beta
layout(set = 0, binding = 4, std430) buffer O { float v[]; } ob;              // (T, h_v, S)
layout(push_constant, std430) uniform PC { int S; int h_k; int h_v; float scale; int T; int row; } pc;

const uint SL = 128u;   // the host wrapper refuses S != 128; constant here because the code below is unrolled

void main() {
    const uint hk = uint(pc.h_k), hv = uint(pc.h_v), T = uint(pc.T), row = uint(pc.row);
    const uint col = gl_GlobalInvocationID.x;           // j fastest, then h: col = h*SL + j
    if (col >= SL * hv) return;
    const uint h = col / SL;
    const uint j = col % SL;
    const uint src = h % hk;                            // MODULO head pairing (not h / (h_v/h_k))
    const uint sbase = h * SL + j;                      // state index base: (i*hv + h)*SL + j
"""

TAIL_LOAD = """    // THE STATE COLUMN: 128 scalars, loaded ONCE per layer (the whole point of this variant).
"""


def emit():
    w = sys.stdout.write
    w(HEAD)
    w(TAIL_LOAD)
    for i in range(SL):
        w("    float s%d = state.v[%du * hv * SL + sbase];\n" % (i, i))
    w("""
    for (uint t = 0u; t < T; ++t) {
        const uint qrow = t * row + src * SL;
        const uint krow = t * row + hk * SL + src * SL;
        const uint vrow = t * row + 2u * hk * SL + h * SL + j;
        const float g = exp(gb.v[t * hv + h]);          // the native body's `g_val = expf(gate[head])`
        const float b = bb.v[t * hv + h];
        // pass 1: the contract against the UNDECAYED state.  ONE accumulator, terms added in ascending `i`.
        float kv = 0.0f;
""")
    for i in range(SL):
        w("        kv += s%d * qkv.v[krow + %du];\n" % (i, i))
    w("""        const float delta = (qkv.v[vrow] - g * kv) * b;
        // pass 2: the folded decay + rank-1 update, then the readout against the UPDATED state.  Same single
        // `attn` accumulator, same ascending order; each term is formed from a load, never from a neighbour's
        // result, exactly as the rolled and KU forms do.
        float attn = 0.0f;
""")
    for i in range(SL):
        w("        { const float n%d = g * s%d + qkv.v[krow + %du] * delta; s%d = n%d; attn += n%d * qkv.v[qrow + %du]; }\n"
          % (i, i, i, i, i, i, i))
    w("""        ob.v[t * (hv * SL) + sbase] = attn * pc.scale;  // the native body's folded 1/sqrt(S) readout scale
    }

    // AND BACK ONCE PER LAYER.
""")
    for i in range(SL):
        w("    state.v[%du * hv * SL + sbase] = s%d;\n" % (i, i))
    w("}\n")


if __name__ == "__main__":
    emit()
